# Conclusions

The decision to install a microgrid at any given location requires the consideration of many factors that are not within the scope of our project, such as the cost of implementation and the actual energy demand of the community or infrastructure in question. There are also many other possible power sources that we did not analyze, such as Combined Heat and Power (CHP) facilities, hydropower, or natural gas. Our results may provide a starting point for discussing microgrid installation, but should not be used to guarantee or discount the feasibility of installation at any given location. Future work will feature an emphasis on which locations have suitable means for powering a microgrid, at a feasible scale.

Not all locations are suitable candidates for DER-powered microgrid installation. Of the zip codes that are suitable based on our results, not all have the same potential for high photovoltaic output.
We identified 10 clusters that categorized each zip code’s characteristics relevant to need and feasibility of DER-powered microgrid installation. With many zip codes having favorable features for a microgrid but not having one yet installed, it is hard to say from a data perspective that microgrids will definitively perform well in these locations, but certain clusters notably had high capacity factors for solar and similar demand profiles indicating the regions are likely solid candidates.

One notable restriction of our analysis was how poorly wind performed. The biggest issue with our assessment of wind is the scale we had to use for our framework. Wind power is proportionate to wind speed cubed, which means averaging wind speed across an entire month will severely undersell average wind power. Additionally, the installation location for wind power is usually a relatively complex process where expected wind gusts are maximized, for example placing a turbine in a naturally occurring wind tunnel between two mountains. Our analysis simply queried the average wind speed at the center of the zip code, which is very unlikely to be any given zip code’s best candidate location. Finally, our data source is simply not meant to capture wind power and is not likely to be a good representation for our purposes. Limitations on API calls and time forced us to under develop this portion of our analysis. 

Future work would likely involve polling each given zip code’s area to find their most suitable locations for a turbine, subsequently polling many times to find average wind speed on a much more fine scale, at least hourly or better, and using that data to estimate wind power. This approach would be much more complex in terms of sampling, and much more demanding in terms of total data required. 

Finally, with all these factors considered, we found that regions with high average wind speeds did not have a notable correlation with wind installations, and regions with high average solar potential did not have a correlation with solar installations. It was notable that by our estimations, a large amount of the continental US showed good solar potential and poor wind potential. There were many confounding variables that outweighed our analysis, such as some existing installations being battery only, some installations being in dense urban areas, and some installations being very small overall. All of these instances might cause a microgrid with good renewable energy potential to not utilize those resources.